spring:
  profiles:
    active: dev

---
server:
  port: 8081

spring:
  profiles: dev
  datasource:
    username: root
    password: 20001030
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  redis:
    port: 6379
    host: 192.168.247.124
    database: 0
  cache:
    type: redis
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
      timeout: 1200



mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zhuhodor.myblog.Entity

logging:
  level:
    com:
      zhuhodor:
        myblog:
          mapper : debug

viewblog:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization




