spring:
  profiles:
    active: dev

---
server:
  port: 8081

spring:
  profiles: dev
  datasource:
    username: root
    password: 20001030
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
    database: 0


mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zhuhodor.myblog.Entity

logging:
  level:
    com:
      zhuhodor:
        myblog:
          mapper : debug

viewblog:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization




